#-----------------------------------------------------------------------------------------------------------------------
# logstash tasks
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

# Include task files in group use
- name: Include ait_role task files
  include: '{{ lookup("first_found", xpack_logstash_task_files) }} ait_args={{ item.args }}'
  with_items: '{{ xpack_logstash_roles[ait_role] }}'
  when: ait_role is defined and xpack_logstash_roles[ait_role] is defined

# Include task files for individual use, keep in sync with vars/main.yml
- name: Include ait_action task files
  include: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_system | lower }}/{{ ait_action }}.yml'
      skip: true
  when: ait_action is defined

# If tasks are for cloud, fail if cloud id is not set 
- fail:
    msg: "Please set env var: ELASTIC_CLOUD_ID to run cloud tasks"
  when: ((ait_role is defined and ait_role | search("cloud")) or
         (ait_action is defined and ait_action | search("cloud"))) and
        (elastic_cloud_id is not defined or not elastic_cloud_id)
