#----------------------------------------------------------------------------------------------------------------------
# Playbook: Test for parity between metricbeat-indexes and internally-indexed Monitoring docs
#
# Author: shaunak@elastic.co
#----------------------------------------------------------------------------------------------------------------------

- hosts: "{{ uut | default(lookup('env','AIT_UUT')) }}"
  roles:
    - role: elasticsearch
    - role: metricbeat

  vars:
    monitoring_docs_dir: "{{ lookup('env', 'WORKSPACE') }}/monitoring/"
    es_docs_query: |
      {
        "query": {
          "bool": {
            "should": [ 
              {
                "bool": {
                  "must_not": [
                    { "term": { "type": "shards" } }
                  ]
                }
              },
              {
                "bool": {
                  "must": [
                    { "term": { "type": "shards" } },
                    { "term": { "shard.state": "STARTED" } }
                  ]
                }
              }
            ]
          }
        },
        "collapse": { "field": "type" },
        "sort": { "timestamp": "desc" }
      }

  vars_files:
    - "{{ es_var_file | default(lookup('env','ANSIBLE_GROUP_VARS')) }}"

  tasks:
    - name: Clean out old directories to hold monitoring sample docs files
      file:
        state: absent
        path: "{{ monitoring_docs_dir }}/elasticsearch"
      delegate_to: localhost

    - name: Make directories to hold monitoring sample docs files
      file:
        state: directory
        path: "{{ monitoring_docs_dir }}/elasticsearch/{{ item }}/"
      with_items:
        - internal
        - metricbeat
      delegate_to: localhost

    - name: Start elasticsearch
      include_role:
        name: xpack_elasticsearch
      vars:
        ait_role: xpack_elasticsearch_install_gencert_config_start_verify

    - name: Enable internal monitoring collection
      uri:
        method: PUT
        url: "https://{{ current_host_ip }}:{{ elasticsearch_port }}/_cluster/settings"
        body: '{ "transient": { "xpack.monitoring.collection.enabled": true } }'
        body_format: json
        validate_certs: no
        user: "{{ elasticsearch_username }}"
        password: "{{ elasticsearch_password }}"
        status_code: 200

    - name: Wait for elasticsearch to index a few monitoring documents
      wait_for:
        timeout: 15

    - name: Get sample elasticsearch-indexed docs from monitoring index
      uri:
        method: POST
        url: "https://{{ current_host_ip }}:{{ elasticsearch_port }}/.monitoring-es-*/_search"
        validate_certs: no
        return_content: yes
        user: "{{ elasticsearch_username }}"
        password: "{{ elasticsearch_password }}"
        body: "{{ es_docs_query }}"
        body_format: json
        status_code: 200
      register: xpack_elasticsearch_monitoring_sample_docs

    - name: Write sample docs to temp files
      copy:
        content: "{{ item._source }}"
        dest: "{{ monitoring_docs_dir }}/elasticsearch/internal/{{ item._source.type }}.json"
      with_items: "{{ xpack_elasticsearch_monitoring_sample_docs.json.hits.hits }}"
      delegate_to: localhost

    - name: Uninstall elasticsearch
      include_role:
        name: elasticsearch
      vars:
        ait_role: elasticsearch_shutdown_uninstall_verify

    - name: Reinstall and restart elasticsearch
      include_role:
        name: xpack_elasticsearch
      vars:
        ait_role: xpack_elasticsearch_install_gencert_config_start_verify

    - name: Install metricbeat
      include_role:
        name: metricbeat
      vars:
        ait_action: metricbeat_install

    - name: Config metricbeat
      include_role:
        name: xpack_metricbeat
      vars:
        ait_action: xpack_metricbeat_config

    - name: Enable metricbeat's elasticsearch module
      shell: '{{ metricbeat_exe }} -c {{ metricbeat_config_file }} modules enable elasticsearch-xpack'
      args:
        executable: /bin/bash
      become: true

    - name: Comment out hosts line in elasticsearch-xpack config file
      become: true
      replace:
        path: '{{ metricbeat_rootdir }}/modules.d/elasticsearch-xpack.yml'
        regexp: 'hosts:'
        replace: '#hosts:'

    - name: Configure elasticsearch-xpack module
      become: true
      blockinfile:
        path: '{{ metricbeat_rootdir  }}/modules.d/elasticsearch-xpack.yml'
        content: |2
            hosts: ["https://{{ current_host_ip  }}:{{ elasticsearch_port  }}"]
            ssl.verification_mode: none
            username: "{{ elasticsearch_username }}"
            password: "{{ elasticsearch_password }}"

    - name: Start metricbeat
      include_role:
        name: xpack_metricbeat
      vars:
        ait_role: xpack_metricbeat_config_start_verify

    - name: Wait for metricbeat to index a few monitoring documents
      wait_for:
        timeout: 15

    - name: Stop metricbeat
      include_role:
        name: metricbeat
      vars:
        ait_action: metricbeat_shutdown

    - name: Get sample metricbeat-indexed docs from monitoring index
      uri:
        url: "https://{{ current_host_ip }}:{{ elasticsearch_port }}/.monitoring-es-*/_search"
        validate_certs: no
        return_content: yes
        user: "{{ elasticsearch_username }}"
        password: "{{ elasticsearch_password }}"
        method: POST
        body: "{{ es_docs_query }}"
        body_format: json
        status_code: 200
      register: xpack_elasticsearch_monitoring_sample_docs

    - name: Write sample docs to temp files
      copy:
        content: "{{ item._source }}"
        dest: "{{ monitoring_docs_dir }}/elasticsearch/metricbeat/{{ item._source.type }}.json"
      with_items: "{{ xpack_elasticsearch_monitoring_sample_docs.json.hits.hits }}"
      delegate_to: localhost

    - name: Stop elasticsearch
      include_role:
        name: elasticsearch
      vars:
        ait_action: elasticsearch_shutdown

    - name: Compare internally-indexed and metricbeat-indexed documents for parity
      shell: 'python {{ playbook_dir }}/docs_compare.py {{ monitoring_docs_dir }}/elasticsearch/internal {{ monitoring_docs_dir }}/elasticsearch/metricbeat'
      delegate_to: localhost
