# AIT environment settings

export AIT_ROOTDIR=$(pwd)

export AIT_SCRIPTS=${AIT_ROOTDIR}/scripts
export PYTHONPATH=${AIT_SCRIPTS}/python/lib

export ANSIBLE_ROOTDIR=${AIT_ROOTDIR}/ansible
export ANSIBLE_CONFIG=${ANSIBLE_ROOTDIR}
export ANSIBLE_LIBRARY=${ANSIBLE_ROOTDIR}/library
export ANSIBLE_GROUP_VARS=${ANSIBLE_ROOTDIR}/group_vars
export ANSIBLE_HOST_VARS=${ANSIBLE_ROOTDIR}/host_vars
export ANSIBLE_ROLES=${ANSIBLE_ROOTDIR}/roles
export ANSIBLE_TEMPLATES=${ANSIBLE_ROOTDIR}/templates
#export ANSIBLE_CALLBACK_PLUGINS=${AIT_ROOTDIR}/ansible/plugins

export AIT_ELASTICSEARCH_USERNAME="elastic"
export AIT_ELASTICSEARCH_PASSWORD="changeme"
export AIT_ELASTICSEARCH_HOST="localhost"
export AIT_ELASTICSEARCH_PORT="9200"
