#-----------------------------------------------------------------------------------------------------------------------
# Check if logstash is not running
#
# Author: liza.dayoub@elastic.co
#-----------------------------------------------------------------------------------------------------------------------
---

- name: Verify logstash is not running
  block:
    - name: Get logstash process
      shell: "ps -efw | grep logstash | grep -v grep | awk '{print $2}'"
      args:
        executable: /bin/bash
      register: logstash_process_id
      retries: 5
      delay: 3
      until: logstash_process_id.stdout == ""
