#----------------------------------------------------------------------------------------------------------------------
# Playbook: Test for parity between metricbeat-indexes and internally-indexed Monitoring docs
#
# Author: shaunak@elastic.co
#----------------------------------------------------------------------------------------------------------------------

- hosts: "{{ uut | default(lookup('env','AIT_UUT')) }}"
  roles:
    - role: elasticsearch
    - role: kibana
    - role: metricbeat

  vars:
    monitoring_docs_dir: "{{ lookup('env', 'WORKSPACE') }}/monitoring/"

  vars_files:
    - "{{ es_var_file | default(lookup('env','ANSIBLE_GROUP_VARS')) }}"

  tasks:
  - include: kibana/docs_parity.yml