# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Vagrant with Ansible configuration
#
# See https://app.vagrantup.com/elastic for boxes available
#
# --

VAGRANTFILE_API_VERSION = "2"

module OS
    def OS.windows?
        (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    end
end

$script = <<-SCRIPT
  # update limits
  LINE1="*        hard    nofile          65536"
  LINE2="*        soft    nofile          65536"
  FILE="/etc/security/limits.conf"
  grep -qF "$LINE1" "$FILE" || echo "$LINE1" >> "$FILE"
  grep -qF "$LINE2" "$FILE" || echo "$LINE2" >> "$FILE"

  # update vm map count
  sysctl -w vm.max_map_count=262144
SCRIPT

VAGRANT_DEFAULT_BOX = "elastic/ubuntu-16.04-x86_64"  # To set use env VAGRANT_BOX
VAGRANT_DEFAULT_MEM = "8192"                         # To set use env VAGRANT_MEM
VAGRANT_DEFAULT_CPU = "4"                            # To set use env VAGRANT_CPU

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  if ENV['ES_BUILD_VAGRANT_BOX']
    config.vm.box = ENV['ES_BUILD_VAGRANT_BOX']
  else
    config.vm.box = VAGRANT_DEFAULT_BOX
  end

  config.vm.network :forwarded_port, guest:5601, host:5601   # kibana
  config.vm.network :forwarded_port, guest:9200, host:9200   # elasticsearch

  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |vb|

    if ENV['ES_BUILD_VAGRANT_MEM']
      vb.memory = ENV['ES_BUILD_VAGRANT_MEM']
    else
      vb.memory = VAGRANT_DEFAULT_MEM
    end

    if ENV['ES_BUILD_VAGRANT_CPU']
      vb.cpus = ENV['ES_BUILD_VAGRANT_CPU']
    else
      vb.cpus = VAGRANT_DEFAULT_CPU
    end

  end

  if ! OS.windows?
    config.vm.provision "shell", inline: $script, privileged: true
  end

  if ENV['ES_BUILD_ANSIBLE_PLAYBOOK']
    config.vm.provision "ansible" do |ansible|
      ansible_host = "vagrant_vm_localhost"
      ansible_var_file = ENV['WORKSPACE'] + "/vars.yml"
      config.vm.define ansible_host 
      ansible.extra_vars = {
        "uut" => ansible_host,  
        "es_var_file" => ansible_var_file 
      }
      ansible.verbose = "v"
      ansible.playbook =  ENV['ES_BUILD_ANSIBLE_PLAYBOOK'] 
    end 
  end
end
